import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import type { ReactNode } from "react";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} dark`}>
      <body>
        <TRPCReactProvider>
          <div className="bg-gradient-to-b from-[#1e543c] to-[#0f1c16] text-white">
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
